version: '3'
services:
  database:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: react-social
      MYSQL_DATABASE: react-social
      MYSQL_USER: react-social
      MYSQL_PASSWORD: react-social