version: '3.3'
services:
    mariadb:
        container_name: react-social
        restart: always
        environment:
          - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
          - MARIADB_DATABASE=react-social
        volumes:
          - '.mysql-data:/var/lib/mysql'
        image: 'mariadb:latest'
        ports:
          - 3306:3306